name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, sqlite

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: /perpustakaan_sekolah

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: /perpustakaan_sekolah

      - name: Build assets with Vite
        run: npm run build
        working-directory: /perpustakaan_sekolah

      - name: Copy .env
        run: cp .env.example .env
        working-directory: /perpustakaan_sekolah

      - name: Generate application key
        run: php artisan key:generate
        working-directory: /perpustakaan_sekolah

      - name: Run migrations
        run: php artisan migrate --force
        working-directory: /perpustakaan_sekolah

      - name: Run tests
        run: php artisan test
        working-directory: /perpustakaan_sekolah
